import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from typing import List, Dict, Optional
from pathlib import Path
from datetime import datetime

from config.settings import Settings

logger = logging.getLogger(__name__)

class EmailNotifier:
    def __init__(self):
        self.settings = Settings()
        
    def send_meeting_summary(
        self,
        recipients: List[str],
        meeting_id: str,
        summary: Dict[str, str],
        transcript_file: Optional[Path] = None,
        audio_file: Optional[Path] = None
    ) -> bool:
        """Send meeting summary email to participants"""
        try:
            # Create email content
            subject = f"Meeting Summary - {meeting_id} - {datetime.now().strftime('%Y-%m-%d')}"
            
            html_content = self._create_summary_html(summary, meeting_id)
            text_content = self._create_summary_text(summary, meeting_id)
            
            # Create message
            msg = MIMEMultipart('alternative')
            msg['Subject'] = subject
            msg['From'] = self.settings.EMAIL_USER
            msg['To'] = ', '.join(recipients)
            
            # Add text and HTML parts
            msg.attach(MIMEText(text_content, 'plain'))
            msg.attach(MIMEText(html_content, 'html'))
            
            # Add attachments if provided
            if transcript_file and transcript_file.exists():
                self._add_attachment(msg, transcript_file)
                
            if audio_file and audio_file.exists():
                self._add_attachment(msg, audio_file)
                
            # Send email
            return self._send_email(msg, recipients)
            
        except Exception as e:
            logger.error(f"Error sending meeting summary: {e}")
            return False
            
    def _create_summary_html(self, summary: Dict[str, str], meeting_id: str) -> str:
        """Create HTML email content"""
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }}
                .header {{ background-color: #f0f0f0; padding: 20px; border-radius: 5px; margin-bottom: 20px; }}
                .section {{ margin-bottom: 20px; }}
                .section h3 {{ color: #333; border-bottom: 2px solid #007bff; padding-bottom: 5px; }}
                .action-item {{ background-color: #fff3cd; padding: 10px; margin: 5px 0; border-radius: 3px; }}
                .footer {{ margin-top: 30px; padding-top: 20px; border-top: 1px solid #ccc; font-size: 12px; color: #666; }}
                ul {{ padding-left: 20px; }}
                li {{ margin: 5px 0; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h2>Meeting Summary</h2>
                <p><strong>Meeting ID:</strong> {meeting_id}</p>
                <p><strong>Date:</strong> {summary.get('date', 'Unknown')}</p>
                <p><strong>Participants:</strong> {summary.get('participants', 'Unknown')}</p>
                <p><strong>Generated by:</strong> {self.settings.AGENT_NAME} AI Meeting Assistant</p>
            </div>
        """
        
        # Add key discussion points
        key_points = summary.get('key_points', '').strip()
        if key_points:
            html += f"""
            <div class="section">
                <h3>Key Discussion Points</h3>
                <div>{self._format_bullet_points(key_points)}</div>
            </div>
            """
            
        # Add action items
        action_items = summary.get('action_items', '').strip()
        if action_items:
            html += f"""
            <div class="section">
                <h3>Action Items</h3>
                <div>{self._format_action_items(action_items)}</div>
            </div>
            """
            
        # Add next steps
        next_steps = summary.get('next_steps', '').strip()
        if next_steps:
            html += f"""
            <div class="section">
                <h3>Next Steps</h3>
                <div>{self._format_bullet_points(next_steps)}</div>
            </div>
            """
            
        # Add insights
        insights = summary.get('insights', '').strip()
        if insights:
            html += f"""
            <div class="section">
                <h3>Key Insights</h3>
                <div>{self._format_bullet_points(insights)}</div>
            </div>
            """
            
        html += """
            <div class="footer">
                <p>This summary was automatically generated by the Dexy AI Meeting Assistant.</p>
                <p>Please review and let us know if any important details were missed.</p>
            </div>
        </body>
        </html>
        """
        
        return html
        
    def _create_summary_text(self, summary: Dict[str, str], meeting_id: str) -> str:
        """Create plain text email content"""
        text = f"""
MEETING SUMMARY
===============

Meeting ID: {meeting_id}
Date: {summary.get('date', 'Unknown')}
Participants: {summary.get('participants', 'Unknown')}
Generated by: {self.settings.AGENT_NAME} AI Meeting Assistant

"""
        
        # Add sections
        sections = [
            ('KEY DISCUSSION POINTS', summary.get('key_points', '')),
            ('ACTION ITEMS', summary.get('action_items', '')),
            ('NEXT STEPS', summary.get('next_steps', '')),
            ('KEY INSIGHTS', summary.get('insights', ''))
        ]
        
        for section_title, content in sections:
            if content.strip():
                text += f"{section_title}\n{'-' * len(section_title)}\n{content.strip()}\n\n"
                
        text += """
---
This summary was automatically generated by the Dexy AI Meeting Assistant.
Please review and let us know if any important details were missed.
"""
        
        return text
        
    def _format_bullet_points(self, text: str) -> str:
        """Format bullet points for HTML"""
        lines = text.split('\n')
        formatted_lines = []
        
        for line in lines:
            line = line.strip()
            if line:
                # Remove existing bullet points
                line = line.lstrip('-•* ')
                if line:
                    formatted_lines.append(f"<li>{line}</li>")
                    
        if formatted_lines:
            return f"<ul>{''.join(formatted_lines)}</ul>"
        return text
        
    def _format_action_items(self, text: str) -> str:
        """Format action items with highlighting"""
        lines = text.split('\n')
        formatted_items = []
        
        for line in lines:
            line = line.strip()
            if line:
                # Remove existing bullet points
                line = line.lstrip('-•* ')
                if line:
                    formatted_items.append(f'<div class="action-item">{line}</div>')
                    
        return ''.join(formatted_items) if formatted_items else text
        
    def _add_attachment(self, msg: MIMEMultipart, file_path: Path):
        """Add file attachment to email"""
        try:
            with open(file_path, 'rb') as attachment:
                part = MIMEBase('application', 'octet-stream')
                part.set_payload(attachment.read())
                
            encoders.encode_base64(part)
            part.add_header(
                'Content-Disposition',
                f'attachment; filename= {file_path.name}'
            )
            
            msg.attach(part)
            logger.info(f"Added attachment: {file_path.name}")
            
        except Exception as e:
            logger.error(f"Error adding attachment {file_path}: {e}")
            
    def _send_email(self, msg: MIMEMultipart, recipients: List[str]) -> bool:
        """Send email using SMTP"""
        try:
            # Create SMTP session
            server = smtplib.SMTP(self.settings.EMAIL_HOST, self.settings.EMAIL_PORT)
            server.starttls()  # Enable TLS
            server.login(self.settings.EMAIL_USER, self.settings.EMAIL_PASSWORD)
            
            # Send email
            text = msg.as_string()
            server.sendmail(self.settings.EMAIL_USER, recipients, text)
            server.quit()
            
            logger.info(f"Email sent successfully to {recipients}")
            return True
            
        except Exception as e:
            logger.error(f"Error sending email: {e}")
            return False
            
    def send_test_email(self, recipient: str) -> bool:
        """Send a test email to verify configuration"""
        try:
            msg = MIMEMultipart()
            msg['Subject'] = f"Test Email from {self.settings.AGENT_NAME}"
            msg['From'] = self.settings.EMAIL_USER
            msg['To'] = recipient
            
            body = f"""
            This is a test email from {self.settings.AGENT_NAME} AI Meeting Assistant.
            
            If you received this email, the email configuration is working correctly.
            
            Time sent: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
            """
            
            msg.attach(MIMEText(body, 'plain'))
            
            return self._send_email(msg, [recipient])
            
        except Exception as e:
            logger.error(f"Error sending test email: {e}")
            return False
            
    def send_action_item_reminder(self, recipients: List[str], action_items: List[Dict]) -> bool:
        """Send action item reminder email"""
        try:
            subject = f"Action Item Reminder - {datetime.now().strftime('%Y-%m-%d')}"
            
            html_content = self._create_reminder_html(action_items)
            text_content = self._create_reminder_text(action_items)
            
            msg = MIMEMultipart('alternative')
            msg['Subject'] = subject
            msg['From'] = self.settings.EMAIL_USER
            msg['To'] = ', '.join(recipients)
            
            msg.attach(MIMEText(text_content, 'plain'))
            msg.attach(MIMEText(html_content, 'html'))
            
            return self._send_email(msg, recipients)
            
        except Exception as e:
            logger.error(f"Error sending action item reminder: {e}")
            return False
            
    def _create_reminder_html(self, action_items: List[Dict]) -> str:
        """Create HTML reminder content"""
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }}
                .header {{ background-color: #fff3cd; padding: 20px; border-radius: 5px; margin-bottom: 20px; }}
                .action-item {{ background-color: #f8f9fa; padding: 15px; margin: 10px 0; border-left: 4px solid #007bff; }}
                .meeting-info {{ font-size: 12px; color: #666; }}
                .footer {{ margin-top: 30px; padding-top: 20px; border-top: 1px solid #ccc; font-size: 12px; color: #666; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h2>Action Item Reminder</h2>
                <p>The following action items are pending from recent meetings:</p>
            </div>
        """
        
        for item in action_items:
            meeting_date = item.get('date', 'Unknown date')[:10]
            html += f"""
            <div class="action-item">
                <strong>{item.get('item', 'Unknown action')}</strong>
                <div class="meeting-info">
                    From meeting: {item.get('meeting_id', 'Unknown')} on {meeting_date}
                </div>
            </div>
            """
            
        html += """
            <div class="footer">
                <p>This reminder was automatically generated by the Dexy AI Meeting Assistant.</p>
            </div>
        </body>
        </html>
        """
        
        return html
        
    def _create_reminder_text(self, action_items: List[Dict]) -> str:
        """Create plain text reminder content"""
        text = f"""
ACTION ITEM REMINDER
===================

The following action items are pending from recent meetings:

"""
        
        for item in action_items:
            meeting_date = item.get('date', 'Unknown date')[:10]
            text += f"• {item.get('item', 'Unknown action')}\n"
            text += f"  From meeting: {item.get('meeting_id', 'Unknown')} on {meeting_date}\n\n"
            
        text += """
---
This reminder was automatically generated by the Dexy AI Meeting Assistant.
"""
        
        return text
        
    def validate_email_config(self) -> bool:
        """Validate email configuration"""
        try:
            if not self.settings.EMAIL_USER or not self.settings.EMAIL_PASSWORD:
                logger.error("Email credentials not configured")
                return False
                
            # Test SMTP connection
            server = smtplib.SMTP(self.settings.EMAIL_HOST, self.settings.EMAIL_PORT)
            server.starttls()
            server.login(self.settings.EMAIL_USER, self.settings.EMAIL_PASSWORD)
            server.quit()
            
            logger.info("Email configuration validated successfully")
            return True
            
        except Exception as e:
            logger.error(f"Email configuration validation failed: {e}")
            return False